# Generated by Django 3.1.1 on 2020-10-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201011_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
